ProjectoFinal/ProjFinal.Backend/Controllers/FaturasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjFinal.Backend.Models;
using ProjFinal.Domain;

namespace ProjFinal.Backend.Controllers
{
    public class FaturasController : Controller
    {
        private DataContextLocal db = new DataContextLocal();

        [Authorize(Roles = "Tecnico")]
        // GET: Faturas
        public ActionResult Index()
        {
            var faturas = db.Faturas.Include(f => f.ProdutoMaquina);
            return View(faturas.ToList());
        }

        [Authorize(Roles = "Tecnico")]
        // GET: Faturas/EscolherMaquina
        public ActionResult EscolherMaquina()
        {
            var maquinas = db.Maquinas.Include(m => m.ModeloMaquina);
            return View(maquinas.ToList());
        }

        [Authorize(Roles = "Tecnico")]
        // GET: Faturas/ProdutosNaMaquina
        public ActionResult ProdutosNaMaquina(int idMaquina)
        {
            //produtos na maquina escolhida
            var produtosMaquina = db.ProdutoMaquinas.Where(p => p.IdMaquina == idMaquina).Include(p=>p.Produto);

            var produtos = produtosMaquina.Select(p => p.Produto);


            ViewBag.IdMaquina = idMaquina;
            return View(produtos);
        }

        [Authorize(Roles = "Tecnico")]
        //// GET: Faturas/ProdutosNaMaquina
        //public ActionResult ProdutosNaMaquina(int idMaquina)
        //{
        //    //produtos na maquina escolhida
        //    var produtosMaquina = db.ProdutoMaquinas.Where(p => p.IdMaquina == idMaquina)
        //        .OrderBy(p => p.IdProduto).Include(p => p.Maquina)
        //        .Include(p => p.Produto);



        //    return View(produtosMaquina);
        //}

        [Authorize(Roles = "Tecnico")]
        // GET: Faturas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fatura fatura = db.Faturas.Find(id);
            if (fatura == null)
            {
                return HttpNotFound();
            }
            return View(fatura);
        }

        [Authorize(Roles = "Tecnico")]
        // GET: Faturas/Create
        public ActionResult Create()
        {
            ViewBag.IdProdutoMaquina = new SelectList(db.ProdutoMaquinas, "IdProdutoMaquina", "IdProdutoMaquina");
            return View();
        }

    
        // POST: Faturas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdFatura,IdProdutoMaquina,Valor,Data")] Fatura fatura)
        {
            if (ModelState.IsValid)
            {
                db.Faturas.Add(fatura);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdProdutoMaquina = new SelectList(db.ProdutoMaquinas, "IdProdutoMaquina", "IdProdutoMaquina", fatura.IdProdutoMaquina);
            return View(fatura);
        }

        [Authorize(Roles = "Tecnico")]
        // GET: Faturas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fatura fatura = db.Faturas.Find(id);
            if (fatura == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdProdutoMaquina = new SelectList(db.ProdutoMaquinas, "IdProdutoMaquina", "IdProdutoMaquina", fatura.IdProdutoMaquina);
            return View(fatura);
        }

      
        // POST: Faturas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdFatura,IdProdutoMaquina,Valor,Data")] Fatura fatura)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fatura).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdProdutoMaquina = new SelectList(db.ProdutoMaquinas, "IdProdutoMaquina", "IdProdutoMaquina", fatura.IdProdutoMaquina);
            return View(fatura);
        }

        [Authorize(Roles = "Tecnico")]
        // GET: Faturas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fatura fatura = db.Faturas.Find(id);
            if (fatura == null)
            {
                return HttpNotFound();
            }
            return View(fatura);
        }

     
        // POST: Faturas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Fatura fatura = db.Faturas.Find(id);
            db.Faturas.Remove(fatura);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Tecnico")]
        // GET: Faturas/Comprar/5
        public ActionResult Comprar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            

            Produto produto = db.Produtoes.Find(id);
            if (produto== null)
            {
                return HttpNotFound();
            }
            return View(produto);
        }

       
        // POST: Faturas/Comprar/5
        [HttpPost, ActionName("Comprar")]
        [ValidateAntiForgeryToken]
        public ActionResult ComprarConfirmed(int id)
        {
            //var produtos = db.ProdutoMaquinas.Where(p => p.IdProduto == id);

            //var idproduto = produtos.Select(p => p.IdProduto);

            var produtosMaquina = db.ProdutoMaquinas.Where(p => p.IdProduto.Equals(id));
            //O que tem a data de validade mais baixa
            ProdutoMaquina produtoARemover = produtosMaquina.OrderBy(a => a.Validade).First();

            db.ProdutoMaquinas.Remove(produtoARemover);
            db.SaveChanges();




            Produto produto = db.Produtoes.Find(produtoARemover.IdProduto);

            Maquina maquina = db.Maquinas.Find(produtoARemover.IdMaquina);

            //Adiciona dinheiro recebido pela comprar
            maquina.DinheiroRecebido = +produto.Preco;
            db.Entry(maquina).State = EntityState.Modified;
            db.SaveChanges();

            //!Não funciona
            //Emissão de fatura/registo de venda
            Fatura fatura = new Fatura
            {
                IdFatura = 0,
                IdProdutoMaquina = produtoARemover.IdProdutoMaquina,
                Valor = produtoARemover.Produto.Preco,
                Data = DateTime.Now.Date
            };
            db.Faturas.Add(fatura);
            db.SaveChanges();


            return RedirectToAction("ProdutosNaMaquina",
                new { idmaquina = produtoARemover.IdMaquina });
        }





        [Authorize(Roles = "Tecnico")]
        // GET: Faturas/Comprar/5
        public ActionResult Comprar2(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProdutoMaquina produtoMaquina = db.ProdutoMaquinas.Find(id);
            if (produtoMaquina == null)
            {
                return HttpNotFound();
            }
            return View(produtoMaquina);
        }

       
        // POST: Faturas/Comprar/5
        [HttpPost, ActionName("Comprar2")]
        [ValidateAntiForgeryToken]
        public ActionResult ComprarConfirmed2(int id)
        {

            ProdutoMaquina produtoMaquina = db.ProdutoMaquinas.Find(id);
            db.ProdutoMaquinas.Remove(produtoMaquina);
            db.SaveChanges();


           

            Produto produto = db.Produtoes.Find(produtoMaquina.IdProduto);

            Maquina maquina = new Maquina();

            //Adiciona dinheiro recebido pela comprar
            maquina.DinheiroRecebido = +produto.Preco;
            db.Entry(maquina).State = EntityState.Modified;
            db.SaveChanges();


            //Emissão de fatura/registo de venda
            Fatura fatura = new Fatura
            {
                IdProdutoMaquina = produtoMaquina.IdProdutoMaquina,
                Valor = produtoMaquina.Produto.Preco,
                Data = DateTime.Now.Date
            };
            db.Faturas.Add(fatura);
            db.SaveChanges();
            

            return RedirectToAction("ProdutosNaMaquina",
                new { idmaquina = produtoMaquina.IdMaquina });
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectoFinal/ProjFinal.Backend/Views/Faturas/Comprar.cshtml
@model ProjFinal.Domain.Produto

@{
    ViewBag.Title = "Comprar";
}

<h2>Comprar?</h2>


<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoriaProduto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoriaProduto)
        </dd>       

        <dt>
            @Html.DisplayNameFor(model => model.Imagem)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imagem)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Comprar" class="btn btn-success" /> |
            @Html.ActionLink("Voltar", "ProdutosNaMaquina", new { idMaquina = ViewBag.IdMaquina})
        </div>
    }
</div>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/Comprar2.cshtml
@model ProjFinal.Domain.ProdutoMaquina

@{
    ViewBag.Title = "Comprar";
}

<h2>Comprar?</h2>


<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Maquina.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maquina.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Produto.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Produto.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Validade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Validade)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Produto.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Produto.Preco)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Comprar" class="btn btn-success" /> |
            @Html.ActionLink("Voltar", "ProdutosNaMaquina",new { idMaquina = Model.IdMaquina })
        </div>
    }
</div>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/Create.cshtml
@model ProjFinal.Domain.Fatura

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Fatura</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.IdProdutoMaquina, "IdProdutoMaquina", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProdutoMaquina", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProdutoMaquina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/Delete.cshtml
@model ProjFinal.Domain.Fatura

@{
    ViewBag.Title = "Delete";
}

<h2>Comprar?</h2>


<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProdutoMaquina.IdProdutoMaquina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoMaquina.IdProdutoMaquina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "ProdutosNaMaquina", new {id=Model.ProdutoMaquina })
        </div>
    }
</div>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/Details.cshtml
@model ProjFinal.Domain.Fatura

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Fatura</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProdutoVendido.IdProdutoMaquina)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdutoVendido.IdProdutoMaquina)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Data)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Data)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdFatura }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/Edit.cshtml
@model ProjFinal.Domain.Fatura

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Fatura</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdFatura)

        <div class="form-group">
            @Html.LabelFor(model => model.IdProdutoMaquina, "IdProdutoMaquina", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProdutoMaquina", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProdutoMaquina, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Data, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/EscolherMaquina.cshtml
@model IEnumerable<ProjFinal.Domain.Maquina>

@{
    ViewBag.Title = "EscolherMaquina";
}

<h2>EscolherMaquina</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdMaquina)
        </th>7
        <th>
            @Html.DisplayNameFor(model => model.nomeUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DinheiroRecebido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Trocos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nomeUser)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdMaquina)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nomeUser)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DinheiroRecebido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Trocos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.idUser)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nomeUser)
        </td>
        <td>
            @Html.ActionLink("Ver produtos na maquina", "ProdutosNaMaquina", "Faturas", new { idMaquina = item.IdMaquina }, new { @class = "btn btn-info" })

        </td>
    </tr>
}

</table>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/Index.cshtml
@model IEnumerable<ProjFinal.Domain.Fatura>

@{
    ViewBag.Title = "Index";
}

<h2>Escolher Produto a Comprar</h2>


<p>
    @Html.ActionLink("Escolher Maquina para Comprar", "EscolherMaquina")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProdutoMaquina.IdProdutoMaquina)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Data)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProdutoMaquina.IdProdutoMaquina)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Data)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.IdFatura }) |
                @Html.ActionLink("Details", "Details", new { id = item.IdFatura }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.IdFatura })
            </td>
        </tr>
    }

</table>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/ProdutosNaMaquina.cshtml
@model IEnumerable<ProjFinal.Domain.Produto>

@{
    ViewBag.Title = "ProdutosNaMaquina";
}

<h2>ProdutosNaMaquina</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Preco)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoriaProduto)
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.Imagem)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Preco)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoriaProduto)
        </td>
      
        <td>
            @Html.DisplayFor(modelItem => item.Imagem)
        </td>
        <td>
        <td>
            @Html.ActionLink("Comprar", "Comprar", new { id = item.IdProduto }, new { @class = "btn btn-success" })
        </td>
    
    </tr>
}

</table>

ProjectoFinal/ProjFinal.Backend/Views/Faturas/ProdutosNaMaquina2.cshtml
@model IEnumerable<ProjFinal.Domain.ProdutoMaquina>

@{
    ViewBag.Title = "ProdutosNaMaquina";
}

<h2>Escolher Produto a Comprar</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Maquina.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Produto.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Validade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Maquina.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Produto.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Validade)
        </td>
        <td>           
            @Html.ActionLink("Comprar", "Comprar", new { id=item.IdProdutoMaquina }, new { @class="btn btn-success"})
        </td>
    </tr>
}

</table>