ProjectoFinal/ProjFinal.Backend/Controllers/MaquinasController.cs
namespace ProjFinal.Backend.Controllers
{
    using System.Data;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    using ProjFinal.Backend.Models;
    using ProjFinal.Domain;
    using ProjFinal.Backend.Helpers;
    using System.Collections.Generic;

    public class MaquinasController : Controller
    {

        private DataContextLocal db = new DataContextLocal();

        [Authorize(Roles = "Tecnico")]
        // GET: Maquinas
        public ActionResult Index()
        {
            var maquinas = db.Maquinas.Include(m => m.ModeloMaquina);
            return View(maquinas.ToList());
        }

        [Authorize(Roles = "Tecnico")]
        // GET: Maquinas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maquina maquina = db.Maquinas.Find(id);
            if (maquina == null)
            {
                return HttpNotFound();
            }
            return View(maquina);
        }

        [Authorize(Roles = "Admin")]
        // GET: Maquinas/Create
        public ActionResult Create(int? idModeloMaquina)
        {
            var nomeModeloMaquina = db.ModeloMaquinas.FirstOrDefault(mm => mm.IdModeloMaquina == idModeloMaquina);

            ViewBag.IdModeloMaquina = new SelectList(db.ModeloMaquinas, "IdModeloMaquina", "Modelo");
            ViewBag.ModeloMaquina = idModeloMaquina;
            ViewBag.NomeModeloMaquina = nomeModeloMaquina;
            return View();
        }


        // POST: Maquinas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdMaquina,IdModeloMaquina,DinheiroRecebido,Trocos,Descricao,idUser,nomeUser")] Maquina maquina)
        {

            if (ModelState.IsValid)
            {
                //Dados de maquina recem criada
                maquina.DinheiroRecebido = 0;
                maquina.Trocos = 0;
                maquina.nomeUser = "Não atribuido";

                db.Maquinas.Add(maquina);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdModeloMaquina = new SelectList(db.ModeloMaquinas, "IdModeloMaquina", "Modelo");
            ViewBag.Error = "Maquina não criada";
            return View(maquina);
        }


        [Authorize(Roles = "Admin")]
        // GET: Maquinas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maquina maquina = db.Maquinas.Find(id);
            if (maquina == null)
            {
                return HttpNotFound();
            }

            ViewBag.Users = new SelectList(CombosHelpers.GetUsers(), "", "");
            ViewBag.IdModeloMaquina = new SelectList(db.ModeloMaquinas, "IdModeloMaquina", "Marca", maquina.IdModeloMaquina);
            return View(maquina);
        }

        // POST: Maquinas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdMaquina,IdModeloMaquina,DinheiroRecebido,Trocos,Descricao,idUser,nomeUser")] Maquina maquina)
        {
            if (ModelState.IsValid)
            {
                db.Entry(maquina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.IdModeloMaquina = new SelectList(db.ModeloMaquinas, "IdModeloMaquina", "Marca", maquina.IdModeloMaquina);
            return View(maquina);
        }



        [Authorize(Roles = "Admin")]
        // GET: Maquinas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maquina maquina = db.Maquinas.Find(id);
            if (maquina == null)
            {
                return HttpNotFound();
            }
            return View(maquina);
        }

        // POST: Maquinas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Maquina maquina = db.Maquinas.Find(id);
            db.Maquinas.Remove(maquina);
            db.SaveChanges();
            return RedirectToAction("Index");
        }





        [Authorize(Roles = "Admin")]
        // GET: Maquinas/AtribuirUser/5
        public ActionResult AtribuirUser(int? idMaquina)
        {
            if (idMaquina == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Maquina maquina = db.Maquinas.Find(idMaquina);
            if (maquina == null)
            {
                return HttpNotFound();
            }



           
            ViewBag.IdMaquina = idMaquina;
            return View(maquina);
        }



        // POST: Maquinas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AtribuirUser(Maquina maquina)
        {
            var maquineta = db.Maquinas.Find(maquina.IdMaquina);

            maquineta.nomeUser = maquina.nomeUser;
            db.Entry(maquineta).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("ListaMaquinasUser");
        }


        [Authorize(Roles = "Tecnico")]
        // GET: Maquinas
        public ActionResult ListaMaquinasUser()
        {
            var maquinas = db.Maquinas.Include(m => m.ModeloMaquina);
            return View(maquinas.ToList());
        }


        [Authorize(Roles = "Tecnico")]
        // GET: Maquinas/GerirMaquina/5
        public ActionResult GerirMaquina(int? idMaquina)
        {
            if (idMaquina == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Maquina maquina = db.Maquinas.Find(idMaquina);
            if (maquina == null)
            {
                return HttpNotFound();
            }

            var alertas = db.Alertas.Where(a => a.IdMaquina == idMaquina);

            ViewBag.Alertas = alertas.Count();
            ViewBag.IdMaquina = idMaquina;
            return View(maquina);
        }



        // POST: Maquinas/GerirMaquina/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GerirMaquina(int idmaquina)
        {

            Maquina maquina = new Maquina();


            //Maquina
            maquina = db.Maquinas.FirstOrDefault(m => m.IdMaquina == idmaquina);

            //Retirar dinheiro recebido da máquina
            maquina.DinheiroRecebido = 0;


            //modelo da maquina
            var modelo = db.ModeloMaquinas.FirstOrDefault(mm => mm.IdModeloMaquina == maquina.IdModeloMaquina);

            //Reposição da quantidade máxima de trocos
            maquina.Trocos = modelo.CapacidadeTrocos;




            if (ModelState.IsValid)
            {

                db.Entry(maquina).State = EntityState.Modified;
                db.SaveChanges();
                return View(maquina);
            }

            ViewBag.IdMaquina = idmaquina;
            ViewBag.Error = "Problema técnico na reposição do dinheiro";
            return View(maquina);
        }




        [Authorize(Roles = "Admin")]
        // GET: Maquinas/ModeloMaquinas
        public ActionResult ModeloMaquinas()
        {
            return View(db.ModeloMaquinas.ToList());
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectoFinal/ProjFinal.Backend/Controllers/UsersController.cs
namespace ProjFinal.Backend.Controllers
{
    using System;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    using ProjFinal.Backend.Helpers;
    using ProjFinal.Backend.Models;
    using ProjFinal.Backend.ViewModels;
    using System.Collections.Generic;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;

    public class UsersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Users
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var users = userManager.Users.ToList();
            var usersView = new List<UserView>();

            foreach (var user in users)
            {
                var userView = new UserView
                {
                    Email = user.Email,
                    Name = user.UserName,
                    UserId = user.Id
                };

                usersView.Add(userView);
            }

            return View(usersView);
        }



        // GET: Roles/Roles
        [Authorize(Roles = "Admin")]
        public ActionResult Roles(string userID)
        {

            //Quando o Id é nulo ou quando passamos um Id que não existe
            if (string.IsNullOrEmpty(userID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            var roles = roleManager.Roles.ToList();
            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == userID);

            if (user == null)
            {
                return HttpNotFound();
            }


            var rolesView = new List<RoleView>();
            foreach (var item in user.Roles)
            {
                var role = roles.Find(r => r.Id == item.RoleId);
                var roleView = new RoleView
                {
                    RoleID = role.Id,
                    Name = role.Name

                };

                rolesView.Add(roleView);
            }

            var userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                UserId = user.Id,
                Roles = rolesView
            };


            return View(userView);
        }


        // GET: Roles/addRole/1
        [Authorize(Roles = "Admin")]
        public ActionResult AddRole(string userID)
        {
            if (string.IsNullOrEmpty(userID))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));

            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == userID);

            if (user == null)
            {
                return HttpNotFound();
            }

            var userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                UserId = user.Id

            };

            ViewBag.RoleID = new SelectList(CombosHelpers.GetRoles(), "Id", "Name");
            //ViewBag.UserName = user.UserName;
            return View(userView);
        }

        [HttpPost]
        public ActionResult AddRole(string userID, FormCollection form)
        {
            var roleId = Request["RoleID"];

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var users = userManager.Users.ToList();
            var user = users.Find(u => u.Id == userID);

            var userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                UserId = user.Id

            };


            if (string.IsNullOrEmpty(roleId))
            {

                ViewBag.RoleID = new SelectList(CombosHelpers.GetRoles(), "Id", "Name");
                ViewBag.Error = "Tem que seleccionar uma permissão..";
            }


            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            var roles = roleManager.Roles.ToList();

            var role = roles.Find(r => r.Id == roleId);

            if (!userManager.IsInRole(userID, role.Name))
            {
                userManager.AddToRole(userID, role.Name);
            }


            var rolesView = new List<RoleView>();
            foreach (var item in user.Roles)
            {
                role = roles.Find(r => r.Id == item.RoleId);
                var roleView = new RoleView
                {
                    RoleID = role.Id,
                    Name = role.Name

                };

                rolesView.Add(roleView);
            }

            userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                UserId = user.Id,
                Roles = rolesView
            };

            return View("Roles", userView);

        }

        // GET: Roles/Delete
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(string userID, string roleID)
        {
            if (string.IsNullOrEmpty(userID) || string.IsNullOrEmpty((roleID)))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(db));

            var user = userManager.Users.ToList().Find(u => u.Id == userID);
            var role = roleManager.Roles.ToList().Find(r => r.Id == roleID);

            //apagar o user dete role
            if (userManager.IsInRole(user.Id, role.Name))
            {
                userManager.RemoveFromRole(user.Id, role.Name);
            }

            //preparar a view

            var users = userManager.Users.ToList();
            var roles = roleManager.Roles.ToList();
            var rolesView = new List<RoleView>();


            foreach (var item in user.Roles)
            {
                role = roles.Find(r => r.Id == item.RoleId);
                var roleView = new RoleView
                {
                    RoleID = role.Name,
                    Name = role.Id

                };

                rolesView.Add(roleView);
            }


            var userView = new UserView
            {
                Email = user.Email,
                Name = user.UserName,
                UserId = user.Id,
                Roles = rolesView
            };

            return View("Roles", userView);
        }





        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectoFinal/ProjFinal.Backend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>

                </button>
               

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a href='@Url.Action("Index", "Home")'>
                            <span class="glyphicon glyphicon-home"></span>
                        </a>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="glyphicon glyphicon-cog"></span>
                            Maquinas<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista de Maquinas", "Index", "Maquinas")</li>
                            <li>@Html.ActionLink("Modelos de Maquina", "Index", "ModeloMaquinas")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="glyphicon glyphicon-cutlery"></span>
                            Produtos<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista de Produtos", "Index", "Produtoes")</li>
                            <li>@Html.ActionLink("Produtos nas Maquinas", "TodosProdutosNasMaquinas", "ProdutoMaquinas")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="glyphicon glyphicon-warning-sign"></span>
                            Alertas<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li> @Html.ActionLink("Alertas", "Index", "Alertas")</li>

                        </ul>
                    </li>
                    <li>
                        
                       
                    </li>



                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="glyphicon glyphicon-user"></span>
                            Gestão de Users<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Permissões", "Index", "Users")</li>
                            <li>@Html.ActionLink("Atribuir user a Maquina", "ListaMaquinasUser", "Maquinas")</li>

                        </ul>

                </ul>





                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
   
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy;CINEL @DateTime.Now.Year - Vending Software </p>
        </footer>
    </div>   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>