ProjectoFinal/MVC_ProjFinal/Controllers/MaquinasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_ProjFinal.Models;

namespace MVC_ProjFinal.Controllers
{
    public class MaquinasController : Controller
    {
        private MVC_ProjFinalContext db = new MVC_ProjFinalContext();

        
    }
}

ProjectoFinal/MVC_ProjFinal/Controllers/ModeloMaquinasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_ProjFinal.Models;

namespace MVC_ProjFinal.Controllers
{
    public class ModeloMaquinasController : Controller
    {
        private MVC_ProjFinalContext db = new MVC_ProjFinalContext();

        
    }
}

ProjectoFinal/MVC_ProjFinal/Controllers/ProdutoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVC_ProjFinal.Models;

namespace MVC_ProjFinal.Controllers
{
    public class ProdutoesController : Controller
    {
        private MVC_ProjFinalContext db = new MVC_ProjFinalContext();

      
    }
}

ProjectoFinal/MVC_ProjFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- @Html.ActionLink("Vending", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })-->
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li>
                        <a href='@Url.Action("Index", "Home")'>
                            <span class="glyphicon glyphicon-home"></span>
                        </a>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="glyphicon glyphicon-cog"></span>
                            Maquinas<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista de Maquinas", "Index", "Maquinas")</li>
                            <li>@Html.ActionLink("Modelos de Maquina", "Index", "ModeloMaquinas")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="glyphicon glyphicon-cutlery"></span>
                            Produtos<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Lista de Produtos", "Index", "Produtoes")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Alertas", "Index", "Alertas")</li>
                   
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="glyphicon glyphicon-euro"></span>
                            Simular Vendas<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Vendas", "Index", "Faturas")</li>
                            <li>@Html.ActionLink("Produtos nas Faturas", "Index", "FaturaProdutoes")</li>
                        </ul>
                </ul>



                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>